# Generated by Django 5.1 on 2024-09-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0004_alter_agendamento_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='horario',
            field=models.CharField(choices=[('7:50 a 8:00', '7:50 a 8:00'), ('11:00 a 11:15', '11:00 a 11:15')], default='7:50 a 8:00', max_length=20),
        ),
    ]
