# Generated by Django 5.1 on 2024-11-13 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alimento_carboidratos_alimento_carboidratos_liquidos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alimento',
            name='quantidade_gml',
        ),
    ]
