# Generated by Django 5.1 on 2024-08-14 16:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
                ('senha', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(8)])),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Nutricionista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=30)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='nutricionita_foto/')),
                ('email', models.EmailField(max_length=100)),
                ('ra', models.CharField(max_length=15)),
                ('senha', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(8)])),
            ],
            options={
                'verbose_name': 'Nutricionista',
                'verbose_name_plural': 'Nutricionistas',
            },
        ),
    ]
