# Generated by Django 5.1 on 2024-08-28 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='nutricionista',
            options={'verbose_name': 'Nutricionista', 'verbose_name_plural': 'Nutricionistas'},
        ),
    ]
