# Generated by Django 5.1 on 2024-08-28 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
