# Generated by Django 5.1 on 2024-08-28 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_alter_user_managers_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
