# Generated by Django 5.1 on 2024-08-30 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0022_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'permissions': [('cliente', 'Pode visitar sua pagina de cliente')], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='nutricionista',
            options={'permissions': [('nutricionista', 'Pode visitar sua pagina de nutricionista')], 'verbose_name': 'Nutricionista', 'verbose_name_plural': 'Nutricionistas'},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='nutricionista',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='nutricionista',
            name='foto',
        ),
        migrations.AddField(
            model_name='user',
            name='data_nascimento',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='user',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto_usuario/'),
        ),
    ]
